# Generated by Django 5.2.2 on 2025-06-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='contenido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_contenido/'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='texto_completo',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
